### ISSUE TITLE
not working correctly (latest stable)

### ISSUE THREAD

**Issue by XPower7125** [LyGhT1337/DiscordDarkness#11]
just installed and something looks off
![image](https://user-images.githubusercontent.com/64551044/218308825-a0be9b10-125d-473f-b357-c8d63538b653.png)
![image](https://user-images.githubusercontent.com/64551044/218308838-eaaced20-1b9e-4baf-977f-4c4d98ab8884.png)

**Comment by YamiK367** [comment]
Heya!

What version of Replugged are you using if I may ask?

I neither have the issue on Stable, nor Canary on the newest version of Replugged.

![image](https://user-images.githubusercontent.com/37241762/218335467-49cd1c48-d9bb-425a-bc41-5c38142ed0ce.png)

**Comment by YamiK367** [comment]
As there is no response I will be continuing with the closure of this issue.

Feel free to open a new one if the issue persists or to contact me on Discord.
