### ISSUE TITLE
Any idea why code block displays extra numbers?

### ISSUE THREAD

**Issue by null15** [LyGhT1337/DiscordDarkness#4]
![image](https://user-images.githubusercontent.com/30800470/112519517-bcfb5500-8d9a-11eb-9655-b741865acd0d.png)

If I disable the theme, it fixes so I'm sure its the theme. But I'm not sure which value in the css I should edit to fix it

**Comment by YamiK367** [comment]
![grafik](https://user-images.githubusercontent.com/37241762/112609627-09d34000-8e1c-11eb-8ab7-8f317cd529fe.png)
Unsure why it looks like that for you, got any other plugins / Themes running on side?

**Comment by YamiK367** [comment]
And if that is supposed to be the CSS editor, it looks normal for me aswell 
![grafik](https://user-images.githubusercontent.com/37241762/112609749-338c6700-8e1c-11eb-8808-969db35288fa.png)

**Comment by null15** [comment]
Hi! Turns out it was the popular Shiki plugin, I disabled it since they don't seem compatible

**Comment by null15** [comment]
Could a plugin perhaps cause this too? 
![image](https://user-images.githubusercontent.com/30800470/112669500-14afc400-8e60-11eb-899b-b593f2b8413c.png)

**Comment by null15** [comment]
Yeah, better codeblocks plugin also did this, for now I deleted them both, so now it works! Although now I can't copy :(

Do you know how to make them compatible with the theme?

**Comment by null15** [comment]
https://github.com/Vap0r1ze/vpc-shiki

**Comment by YamiK367** [comment]
Issue is, both are touching the Codeblocks side of Discord, meaning if I was gonna add them together in any way I'd need the approval from the creator of shiki to use it in my theme. So as of now, even if I wanted to, tried to and maybe get it to work.. I wouldn't be able to publish it onto my Theme.

I know this response is a bit late, but lately I've been busy with alot of irl stuff D:
