### ISSUE TITLE
Server Folders backgrounds are not themed correctly 

### ISSUE THREAD

**Issue by Davoleo** [LyGhT1337/DiscordDarkness#5]
Seems like server folders are not themed correctly
![image](https://user-images.githubusercontent.com/24458276/118375044-77e7e800-b5bf-11eb-918b-34c389f01845.png)

**Comment by YamiK367** [comment]
Will take a look at it later this evening, got to fix reactions aswell and Role Settings seem not to be 100% fixed yet, so imma look at it this evening, thanks for reporting!

**Comment by YamiK367** [comment]
Temporary fix should be pushed and fix the issue, if not please report back ^_^

**Comment by Davoleo** [comment]
![image](https://user-images.githubusercontent.com/24458276/118414868-60842a00-b6a7-11eb-8fb8-8c9dd581899d.png)
mmh seems like it didn't work

I've also noticed another minor issue in the "Active Now" panel of the home page
The background doens't change to the dark shade

**Comment by YamiK367** [comment]
I know this is a bit late of an response, but it should have been fixed by now :

![grafik](https://user-images.githubusercontent.com/37241762/119714956-bd2fd380-be63-11eb-9b48-4739ec44c0c7.png)

![grafik](https://user-images.githubusercontent.com/37241762/119714988-c882ff00-be63-11eb-93a0-054d14a0367f.png)

**Comment by Davoleo** [comment]
oh yeah the Active now panel is themed for me as well, and the server folders background don't have that square background under the icon, but for some reason the background of server folders when expanded is still the old one
![image](https://user-images.githubusercontent.com/24458276/119728844-33d4cd00-be74-11eb-883f-a6281f8a46b2.png)
maybe it has something to do with the fact they also seem like they're cut when collapsed 🤔 
![image](https://user-images.githubusercontent.com/24458276/119728988-67aff280-be74-11eb-8d11-7689330260fd.png)
_(btw I have triple checked now, and I'm on the latest commit of the theme)_

anyways it's not a big deal, might be some specific thing on my end, thanks for all the fixes it's already a lot better than before

**Comment by YamiK367** [comment]
![grafik](https://user-images.githubusercontent.com/37241762/120043512-644f6f00-c00c-11eb-8489-a6a7c6e070b8.png)

This is what I ended up with, it's how it previously has been

**Comment by Davoleo** [comment]
nice, I'll close this issue, thanks for all the fixes
