### ISSUE TITLE
Newest Discord Canary updates broke this theme for both Powercord and BD Canary

### ISSUE THREAD

**Issue by MIHAIdavid22** [LyGhT1337/DiscordDarkness#6]
It appears the latest Canary update has broken this theme on Powercord and i believe on Betterdiscord Canary aswell,The devtools console in Discord Canary does not show any error relating to the theme as far as i had tried, however the main culprit is speculated to be re-rolling certain class names or at the very least that is what has been communicated to me as to why this theme is broken, and no longer loads with Discord Canary at all.

**Comment by YamiK367** [comment]
Yup it's known and I am working on it at the moment -  every theme has basically been destroyed through discord replacing 99% of all the classes by new ones.
-> 

But yeah working on it as fast as i can

![grafik](https://user-images.githubusercontent.com/37241762/148661058-9af63c0b-8f6c-4994-9c72-55c30feaafe5.png)

**Comment by YamiK367** [comment]
@MIHAIdavid22 ALOT has been fixed with that push now, some things are still meh but thats work for tomorrow! gn8 :D

**Comment by MIHAIdavid22** [comment]
It appears whatever update has been pushed has broken Powercord once again,this time i actually have a Devtools Console Log
![image](https://user-images.githubusercontent.com/20879176/148687739-bddf3e10-1cba-4932-b17f-901c210e15e1.png)
Do not know if it's only a issue on my end or if it affects all Powercord users

**Comment by YamiK367** [comment]
However that caused it, it should be fixed again

Atleast exact Github Branch is what I am using on Powercord atm with no error like that

**Comment by MIHAIdavid22** [comment]
Thank you,have a good day
