### ISSUE TITLE
Folder weirdness

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [LyGhT1337/DiscordDarkness#7]
Folders for guilds look very weird and dont have proper square edges, I assume due to the themepocalypse discord caused.
![image](https://user-images.githubusercontent.com/62061444/148997467-de41d429-22e8-407f-a97f-71e92d1e8c54.png)

**Comment by YamiK367** [comment]
Gonna try to fix it asap, today

**Comment by YamiK367** [comment]
@TranquillyUnpleasant 

Fix is out!

![grafik](https://user-images.githubusercontent.com/37241762/149326061-787393f7-69c0-4cbb-b2ee-f59651843fd2.png)
