### ISSUE TITLE
Better compatibility with other Powercord Plugins

### ISSUE THREAD

**Issue by MIHAIdavid22** [LyGhT1337/DiscordDarkness#9]
While not really important i would like if there was better compatibility with other Powercord plugins such as
User Details by Juby210 [https://github.com/Juby210/user-details](url) 
Because of an commit quite a while ago,In which the User Popout Modal was changed, the plugin above no longer displays correctly the information the plugin provides
For example : 
![image](https://user-images.githubusercontent.com/20879176/155825022-e89d9234-e828-4807-9e58-563372fc2685.png)
There should be a Created at:"information" above Joined At:"information"

**This is meerly an suggestion and nothing more**, I am sorry for troubling you with this.

**Comment by YamiK367** [comment]
I'll see right now what I can do to fix it, give me a few minutes

**Comment by YamiK367** [comment]
Since as you said that above plugin doesn't work correctly anymore, are there any "specific" plugins u'd like better support for?

If yes, please link em as a comment so I can see what I can do and I'll gladly try my best to make em fit the theme better!
